### ISSUE TITLE
busted homebrew formula

### ISSUE THREAD

**Issue by mcandre** [peterklijn/hammerspoon-shiftit#31]
Hi,

The install steps and fundamental configuration are really confusing.

Please fix the Homebrew formula so that the example configurations no longer produce nil index errors out of the box. For example, go ahead and ship the default spoon(s) as a post-install step in the Homebrew formula.

For now, I'm sticking with the classic ShiftIt application rather than Hammerspoon.

While the classic ShiftIt sucks at cohabitating with Zoom and other videoconferencing apps, at least the basic GUI and documentation are more intuitive.

**Comment by peterklijn** [comment]
Hey Andrew, thanks for reporting the issue, I'll have a look soon and get back to you.
I don't use homebrew to install this spoon, and wasn't aware it doesn't work (anymore)

**Comment by peterklijn** [comment]
Hey @mcandre,
It took a bit longer to look into the issue, could you help me out by providing some more information?

The only brew commands in the readme are regarding installing Hammerspoon itself, not this specific spoon. I tried installing Hammerspoon via brew, which initially failed because I already had it installed, but after deleting it and running the command again, the installation worked fine..
(Also, apart from the the argument order, they're also inline with [Hammerspoon's own readme](https://github.com/Hammerspoon/hammerspoon#homebrew))


First install, failed due to already existing install:
```bash
➜  ~ brew install --cask hammerspoon
Running `brew update --preinstall`...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:905b0c3896164ae8067a22fff2fd0b80b16d3c8bb72441403eedf69da71ec717
######################################################################################################################################################### 100.0%
==> Pouring portable-ruby-2.6.10_1.arm64_big_sur.bottle.tar.gz
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################### 100.0%
==> Downloading https://github.com/Hammerspoon/hammerspoon/releases/download/0.9.100/Hammerspoon-0.9.100.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/24956772/5dd314fd-a19a-4293-8f50-cdcfdf19c0fb?X-Amz-Algorithm=
######################################################################################################################################################### 100.0%
==> Installing Cask hammerspoon
==> Purging files for version 0.9.100 of Cask hammerspoon
Error: It seems there is already an App at '/Applications/Hammerspoon.app'.
```

Second install, after removing the previous install:
```bash
➜  ~ brew install --cask hammerspoon
==> Downloading https://github.com/Hammerspoon/hammerspoon/releases/download/0.9.100/Hammerspoon-0.9.100.zip
Already downloaded: /Users/peter/Library/Caches/Homebrew/downloads/7c4b240f024c93ab41bbec81435d3c69f8fe1cc3ed9fc281413b0f07c56d20c3--Hammerspoon-0.9.100.zip
==> Installing Cask hammerspoon
==> Moving App 'Hammerspoon.app' to '/Applications/Hammerspoon.app'
🍺  hammerspoon was successfully installed!
```

Any chance you simply experienced a fluke while installing when you made this ticket?

All subsequent steps don't involve brew, if any of them are unclear and you have some suggestions on how to improve them, I'm happy to hear it :)
