### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by shyshywhy** [peterklijn/hammerspoon-shiftit#7]
2020-09-01 14:31:39: ********
2020-09-01 14:31:39: ********
2020-09-01 14:31:39: 14:31:39 ERROR:   LuaSkin: hs.hotkey callback: /Users/lewin/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:51: attempt to index a nil value
stack traceback:
	/Users/lewin/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:51: in function 'move'
	/Users/lewin/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:115: in function 'ShiftIt.up'
	/Users/lewin/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:163: in function </Users/lewin/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:163>
2020-09-01 14:31:39: ********

**Comment by peterklijn** [comment]
Hi @shyshywhy,

I think this is [the same issue](https://github.com/peterklijn/hammerspoon-shiftit/issues/5) as reported here.

Could you please check [this comment](https://github.com/peterklijn/hammerspoon-shiftit/issues/5#issuecomment-672906472).

Thanks, 
Peter

**Comment by deldrid1** [comment]
@peterklijn - I've used this this plugin since ShiftIt went EOL.  Unfortunately, I've started seeing the same error message intermittently on different applications.  This may be a problem with hammerspoon itself - I'm not 100% sure, but I think I started seeing this issue when a new version was released about 10 days ago.  Unfortunately, downgrading back to [0.9.78](https://github.com/Hammerspoon/hammerspoon/releases/tag/0.9.78) didn't help...

I have the Accessibility option checked.  
![image](https://user-images.githubusercontent.com/583660/94691035-d4cbb200-02fe-11eb-901f-68ccf5babb5d.png)

As an example, the Chrome browser that I am typing this issue in resizes just fine with no console output in hammerspoon.  

However, if I bring Microsoft Excel the foreground and attempt to resize it, I get the same error as @shyshywhy.  I'm on macOS 10.15.6.

```
2020-09-30 09:26:04: 09:26:04 ERROR:   LuaSkin: hs.hotkey callback: ...ustineldridge/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:51: attempt to index a nil value
stack traceback:
	...ustineldridge/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:51: in function 'move'
	...ustineldridge/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:115: in function 'ShiftIt.up'
	...ustineldridge/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:163: in function <...ustineldridge/.hammerspoon/Spoons/ShiftIt.spoon/init.lua:163>
```

**Comment by peterklijn** [comment]
Thanks for your reply @deldrid1

From what you say, I think that some applications like Excel either don't respect certain OSX window APIs, or Hammerspoon's `move` command makes some assumptions.

The error that you shared points to [line 51](https://github.com/peterklijn/hammerspoon-shiftit/blob/master/init.lua#L51) of the this plugin, which uses Hammerspoon's [build-in Window:move command](https://www.hammerspoon.org/docs/hs.window.html#move).

As I don't own Microsoft Excel, or any of the products from their suite, I'm not able to reproduce this which makes it really hard to test. Could you report an issue on [Hammerspoon's issue page](https://github.com/Hammerspoon/hammerspoon/issues)?

If you're able to recreate this issue with another application, ideally one that's free, please share so I can reproduce the issue and see if there's something I can solve in this Spoon
